# Generated by Django 5.2 on 2025-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_marketplacelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
