# Generated by Django 5.1.5 on 2025-04-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tradelisting_tradeoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='home.marketplacelisting'),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='desired_pokemon_names',
            field=models.CharField(blank=True, help_text='Comma-separated names of Pokémon the owner wants', max_length=300),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketplacelisting',
            name='status',
            field=models.CharField(choices=[('for sale', 'For Sale'), ('for trade', 'For Trade'), ('for both', 'For Both')], default='for sale', max_length=10),
        ),
        migrations.DeleteModel(
            name='TradeListing',
        ),
    ]
